name: Flutter main ci

on:
  # 手動実行できるようにする。
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: ./mobile/

    timeout-minutes: 10

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'

      - name: Flutter installed check
        run: flutter --version

      # build 確認。
      - name: Build check
        run: flutter build apk 

      # ユニットテストを実行する。
      - name: Run unit test
        run: flutter test
